map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard

# Zoom con el + del keypad (KC_PPLS)
map ctrl+kp_add change_font_size all +2

# Zoom out con -
map ctrl+minus change_font_size all -2

# Reset zoom
map ctrl+0 change_font_size all 0

enable_audio_bell no
visual_bell_duration 0

cursor_blink_interval 0

font_size 11.5

background_opacity 0.6
dynamic_background_opacity yes

shell_integration enabled
tab_title_template '{title}'
